name: Benchmarks

on:
  workflow_dispatch:


jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo apt-get install -y libsuitesparse-dev

      - name: Build Release
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)

      #- name: Run benchmarks
      #  run: |
      #    cd build
      #    echo "Benchmarks will be added later"
